* Bruksområder
** "Hva skjer a"?

*** Send ut en melding til alle venner om de driver med noe, mulighet for å svare med melding, kartmarkering, event.

*** Autosvarer hvis en venn er sjekket inn et sted eller ved en event

** "Skal vi gjøre noe?"

*** Send ut melding til venner om de vil finne på noe, alternativt med forslag til sted/ting

    Lager en event, notifiserer de andre.

** "Vil du være med?"

*** Send ut invitasjon til venner om å være med på en spesifikk event"
* Designvalg
** Kart-sentrisk
*** Kan få opp alle eventer som skjer i ett visst område innen en viss tid, som man har tilgang til
*** Kan "pinge" kartet for å se om folk er interessert i å dra et sted
** "Forespørsel" som design-element
*** Alle forespørsler er community-basert, ala Facebook-events
*** Trådete kommentarer
*** Auto-linker til en event hvis en event oppstår som et resultat av en forespørsel

    Muligens at forespørselen omgjøres automatisk?

** Kan sjekke inn i eventer
*** Separat fra å si at du deltar på forhånd

    Unngå et problem Facebook har, der man ikke kan se hvor mange som var/er med
    på en event, siden mange som sier at de deltar ikke faktisk var der.
*** Automatisk sjekkinn via GPS?

    Mulighet man kan skru av/på
