#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage{hypcap}
#+LATEX_HEADER: \hypersetup{colorlinks=true,linkcolor=red,citecolor=black,filecolor=magenta, urlcolor=cyan}
User interviews

*  First interview

   Interview focusing on initial data gathering, loosely formulated. The points
   below are just points to touch upon, not hard-and-fast questions to follow in
   order. Focus on unique insights.

   1. How do you usually plan small events like movie nights, lunch and the like?

   2. Have you ever used Facebook events? Ever made one yourself?

   3. Have you ever used location-based services such as Gowalla, Foursquare,
      Yelp, Facebook places, or similar?

   4. If you could improve something in either of these (particularly FB Events),
      what would it be?

   5. Would you use an application that lets you plan simple events on a map,
      notify/invite your friends and uses location-based services to track
      check-ins and such.

   6. How would you prefer that such an application notifies you?

   7. Would you allow the application access to your Facebook info to allow the
      application to better recommend and rank events, and other recommendation
      tasks?

   8. Would you want to maintain a friend list, or would you like to join
      "communities" to control who sees your events?

** Interview one

   - Interviewer :: Ok, first of all, you're ok with me adding the transcript of
                    this interview to my report, yes?
   - Interviewee :: Yes
   - Interviewer :: Good. How do you usually plan small events, like movie
                    nights, going out to lunch, or similar?
   - Interviewee :: I don't normally plan ahead of time.  I generally see what
                    I'm in the mood for that day and then send a text out to all
                    of my friends and see who feels like going.
   - Interviewer :: ok, so you usually use texting back and forth to see who can
                    make it?
   - Interviewee :: Yes.
   - Interviewer :: Do you think there could be a better way to do this, that
                    doesn't entail as many texts?
   - Interviewer :: would you want to use one?
   - Interviewee :: I would.
   - Interviewer :: Have you ever used Facebook events? Ever made one yourself?
   - Interviewee :: I have used it before, but I have never made one for myself.
   - Interviewer :: Do you think Facebook Events would work for simple events
                    like mentioned? Why/Why not?
   - Interviewee :: I do not think it would work very well because it seems like
                    it would be a lot of work for such a little thing.
   - Interviewee :: And I don't think enough people would notice it on time.
   - Interviewee :: Especially if it's last minute.
   - Interviewer :: indeed
   - Interviewer :: Have you ever used any location-based social tools, like
                    Gowalla, Foursquare, Yelp, Facebook places or similar?
   - Interviewee :: No
   - Interviewer :: Do you know anything about them?
   - Interviewee :: Very little.
   - Interviewer :: ok, enough to say why you don't use them?
   - Interviewee :: I was kind of interested, but to be honest I couldn't figure
                    out how to use the Facebook one.  I don't know what any of
                    the others are.
   - Interviewer :: ok, I see
   - Interviewer :: So, would you use an application that lets you plan simple
                    events on a map, notify your friends about it, and lets them
                    respond without you needing to send multitudes of texts?
   - Interviewee :: Yes.
   - Interviewer :: Would you allow such an application access to your facebook
                    profile, to allow the application to better recommend events
                    that your friends are planning?
   - Interviewee :: I would.
   - Interviewer :: Would you like to maintain a friend list, or would you like
                    to join "communities" to control who sees your events? In
                    the former case, everyone on your friend's list sees the
                    event, in the latter you'd post to only one community, and
                    everyone in that community sees the event.
   - Interviewee :: I would join communities.
   - Interviewer :: Any particular reason why you'd choose that over a friend
                    list?
   - Interviewee :: Certain people I would like to avoid.
   - Interviewer :: well you could just not add them to your friend list
   - Interviewer :: but ok, that was the questions I had. Do you have any other
                    comments you'd like to come with?
   - Interviewee :: Well I might want to go with certain people for certain
                    things, but not others.
   - Interviewee :: I think that's all.
   - Interviewer :: Ok, thank you :)
   - Interviewee :: You're welcome!
** Interview two
   - Interviewer :: So, first off, are you okay with the transcript of this
                    interview appearing in my report, scrubbed of names?
   - Interviewee :: yep
   - Interviewer :: ok, good. How do you usually plan small events like movie
                    nights, lunch, or similar?
   - Interviewee :: depending on the circle of friends, i do it via im/irc then
                    generally send out an event notice on gcal or facebook
   - Interviewer :: Do you find that this procedure is needlessly complicated?
   - Interviewee :: it could definitely be streamlined, but it's better than it
                    used to be
   - Interviewer :: Have you ever used location-based services such as Gowalla,
                    Foursquare, Yelp, Facebook places or similar?
   - Interviewee :: i've used yelp heavily, mainly to find places to go
   - Interviewer :: Any particular reason you don't use Gowalla or Foursquare?
   - Interviewee :: i've never tried gowalla, but i saw no benefits to
                    foursquare in my limited use
   - Interviewer :: If you could improve on the event planning procedure you
                    use, how would you do it?
   - Interviewee :: i've never really thought about it, but some facility by
                    which people can more easily figure out when their friends
                    are free for things would make things easier
   - Interviewer :: Interesting
   - Interviewer :: Would you use an application that lets you plan these kinds
                    of single events on a map, notify/invite you friends, and
                    optionally uses location to track check-ins to events?
   - Interviewee :: if it makes the actual planning part of it easier
                    (especially scheduling negotiations), absolutely
   - Interviewee :: otherwise, possible
   - Interviewer :: Would you allow the application access to your google
                    calendar schedule (or similar) so it can notify your friends
                    of your availability when they plan events?
   - Interviewee :: yes
   - Interviewer :: Would you allow it access to your facebook info, so it can
                    use your profile data to better recommend/rank events or
                    otherwise use your data to make choosing events to attend to
                    easier?
   - Interviewee :: yes
   - Interviewer :: Would you rather use a friend list, potentially with friend
                    groups, or join "communities" to control who sees your
                    events? A community in this context is a group of people
                    with some relation to eachothers
   - Interviewee :: i don't have a preference either way -- i'd likely use both.
   - Interviewer :: ok, I think that should be all my questions, any other
                    comments?
   - Interviewee :: not off the top of my head
   - Interviewer :: ok, thanks :)

** Interview three
   - Interviewer :: Vel, først må jeg spørre om det er greit at jeg inkluderer
                    en kopi av denne samtalen i rapporten min, med navn fjerna?
   - Interviewee :: sure
   - Interviewee :: skal prøve å ikke si noe upassende
   - Interviewee :: xp
   - Interviewer :: heh
   - Interviewer :: Hvordan pleier du vanligvis å planlegge mindre events, slik
                    som filmkvelder, lunsj, sammenkomster eller lignende?
   - Interviewee :: På facebook eller via meldinger på mobil..evt
                    telefonsamtaler
   - Interviewer :: Syns du denne prosessen er unødvendig komplisert? I så fall,
                    hvordan ville du likt å forbedre den?
   - Interviewee :: Hehe.. nei, jeg kan ikke se for meg at det skal kunne være
                    noe mindre komplisert
   - Interviewer :: Har du noengang brukt facebook-eventer? Noen gang lagd de
                    selv?
   - Interviewee :: Jeg har blitt invitert til noen events som jeg har deltatt
                    på. har aldri lagd noen selv..
   - Interviewee :: Men jeg syns som oftest event-invites er irriterende
   - Interviewee :: det er så mange jeg absolutt ikke vil delta på.. og mange
                    som bare er unødvendige
   - Interviewee :: :P
   - Interviewer :: haha, ok. Har du noen gang brukt lokasjons-baserte
                    tjenester, slik som Gowalla, Foursquare, Facebook places,
                    eller lignende?
   - Interviewee :: ehm.. jeg er ikke kjent med noen av de. men jeg har brukt
                    google streetview, om det faller i den kategorien? :P
   - Interviewer :: Ikke direkte, de nevnte tjenestene deler hvor du oppholder
                    deg, og har slike "check-ins"
   - Interviewee :: okay, nei,det har jeg aldri brukt ;)
   - Interviewer :: Er det noe du syns burde forbedres med facebook events, som
                    ville gjøre det bedre for deg?
   - Interviewee :: Jeg vet ikke om det kanskje går da.. men jeg vil gjerne
                    kunne filtrere bort visse personer sine invites :P f eks
                    ansatte på tiger-tiger og sånn;)
   - Interviewee :: kanskje få en egen liste over events som skjer på skolen
   - Interviewee :: gruppere de , eller no
   - Interviewer :: ok
   - Interviewer :: Ville du tatt i bruk en applikasjon som lar deg planlegge
                    tidligere nevnte simple events på et kart,
                    notifisere/invitere venner og muligens bruker
                    lokasjons-baserte tjenester til å si hvem som har kommet
                    eller ikke?
   - Interviewee :: Brått, hehe. Jeg er ikke supersosial og deltar ikke på så
                    mange events, men når jeg først gjør det hadde det jo vært
                    litt kult. Men jeg hadde nok ikke betalt for det;)
   - Interviewee :: Hvis det var enkelt å innstallere å bruke og "alle andre"
                    brukte det, så hadde jeg nok gjort det jeg også
   - Interviewer :: Siden du ikke er veldig glad i invites/notifikasjoner,
                    hvordan ville du likt at en slik applikasjon notifiserer
                    deg, ville du sett på muligheten til å blokkere invites fra
                    en person som kritisk?
   - Interviewee :: kan du omformulere spørsmålet litt? vet ikke om jeg forstod
                    det helt
   - Interviewer :: vel, todelt. Hvordan ville du likt å få notifikasjoner fra
                    applikasjonen om invites, antatt at dette er på en telefon?
   - Interviewee :: Er applikasjonen knyttet til facebook på noen måte?
   - Interviewer :: det er en mulighet
   - Interviewee :: Det hadde jo vært greit. å få vite om det når jeg logger meg
                    inn der. Evt når jeg logger inn på mail. Vil logge inn selv
                    for å lese, vil ikke at det popper opp noe hele tiden
                    automatisk og kobler seg til nettet uten at jeg vil og
                    sånn :P Og jeg vil jo logge inn på så lite som mulig. så det
                    burde vært på et sted jeg har fra før
   - Interviewee :: om det gir noe mening, hehe
   - Interviewer :: skjønner, så du vil ha mulighet for notifikasjoner andre
                    steder.
   - Interviewee :: ja ;)
   - Interviewer :: det andre punktet, ville du sett på muligheten til å
                    blokkere invites fra en person som kritisk funksjonalitet?
   - Interviewee :: ja, hvis folk spammer..og eneste muligheten å stoppe spammen
                    på er å unfriende de, så er jo det irriterende. jeg vil jo
                    ikke nødvendig unfriende noen bare fordi de sender
                    irriterende invites. muligheten til å blokkere updates på
                    facebook er gull
   - Interviewee :: xp
   - Interviewee :: i hvertfall om jeg fikk en mail hver gang jeg fikk en
                    invite.
   - Interviewer :: Ville du latt applikasjonen få tilgang til Facebook-dataene
                    dine, så den kan bruke de til å anbefale og rangere events,
                    eller å automatisk si ifra til andre om at du er opptatt når
                    de inviterer deg?
   - Interviewee :: i guess, er det ikke det man godtar på nesten alle facebook
                    apps? :P
   - Interviewer :: hehe, det er mulig
   - Interviewee :: siden jeg har gjort det flere ganger før da, uten å tenke
                    meg så mye om, så ser jeg ingen grunn til at jeg ikke hadde
                    gjort det igjen ;)
   - Interviewer :: Vil du heller opprettholde en venneliste (potensielt med
                    grupper), eller vil du heller slutte deg til "communities"
                    for å bestemme hvem som ser eventene dine, og hvem sine
                    eventer du ser?
   - Interviewer :: Med "communities" mener jeg grupper med personer som har en
                    løs tilhørighet til hverandre, så du slipper legge til alle
                    som venn.
   - Interviewee :: uhm jeg vil ha kontroll på alle som ser mine events og hva
                    jeg skal på..
   - Interviewee :: så, bare venner altså
   - Interviewer :: ok
   - Interviewer :: vel, det var vel alle spørsmåla mine :)
   - Interviewee :: okay :D
