User interviews
*  First interview

   Interview focusing on initial data gathering, loosely formulated. The points
   below are just points to touch upon, not hard-and-fast questions to follow in
   order. Focus on unique insights.

   1. How do you usually plan small events like movie nights, lunch and the like?

   2. Have you ever used Facebook events? Ever made one yourself?

   3. Have you ever used location-based services such as Gowalla, Foursquare,
      Yelp, Facebook places, or similar?

   4. If you could improve something in either of these (particularly FB Events),
      what would it be?

   5. Would you use an application that lets you plan simple events on a map,
      notify/invite your friends and uses location-based services to track
      check-ins and such.

   6. How would you prefer that such an application notifies you?

   7. Would you allow the application access to your Facebook info to allow the
      application to better recommend and rank events, and other recommendation
      tasks?

   8. Would you want to maintain a friend list, or would you like to join
      "communities" to control who sees your events?

** Interview one

   - Interviewer :: Ok, first of all, you're ok with me adding the transcript of
                    this interview to my report, yes?
   - Interviewee :: Yes
   - Interviewer :: Good. How do you usually plan small events, like movie
                    nights, going out to lunch, or similar?
   - Interviewee :: I don't normally plan ahead of time.  I generally see what
                    I'm in the mood for that day and then send a text out to all
                    of my friends and see who feels like going.
   - Interviewer :: ok, so you usually use texting back and forth to see who can
                    make it?
   - Interviewee :: Yes.
   - Interviewer :: Do you think there could be a better way to do this, that
                    doesn't entail as many texts?
   - Interviewer :: would you want to use one?
   - Interviewee :: I would.
   - Interviewer :: Have you ever used Facebook events? Ever made one yourself?
   - Interviewee :: I have used it before, but I have never made one for myself.
   - Interviewer :: Do you think Facebook Events would work for simple events
                    like mentioned? Why/Why not?
   - Interviewee :: I do not think it would work very well because it seems like
                    it would be a lot of work for such a little thing.
   - Interviewee :: And I don't think enough people would notice it on time.
   - Interviewee :: Especially if it's last minute.
   - Interviewer :: indeed
   - Interviewer :: Have you ever used any location-based social tools, like
                    Gowalla, Foursquare, Yelp, Facebook places or similar?
   - Interviewee :: No
   - Interviewer :: Do you know anything about them?
   - Interviewee :: Very little.
   - Interviewer :: ok, enough to say why you don't use them?
   - Interviewee :: I was kind of interested, but to be honest I couldn't figure
                    out how to use the Facebook one.  I don't know what any of
                    the others are.
   - Interviewer :: ok, I see
   - Interviewer :: So, would you use an application that lets you plan simple
                    events on a map, notify your friends about it, and lets them
                    respond without you needing to send multitudes of texts?
   - Interviewee :: Yes.
   - Interviewer :: Would you allow such an application access to your facebook
                    profile, to allow the application to better recommend events
                    that your friends are planning?
   - Interviewee :: I would.
   - Interviewer :: Would you like to maintain a friend list, or would you like
                    to join "communities" to control who sees your events? In
                    the former case, everyone on your friend's list sees the
                    event, in the latter you'd post to only one community, and
                    everyone in that community sees the event.
   - Interviewee :: I would join communities.
   - Interviewer :: Any particular reason why you'd choose that over a friend
                    list?
   - Interviewee :: Certain people I would like to avoid.
   - Interviewer :: well you could just not add them to your friend list
   - Interviewer :: but ok, that was the questions I had. Do you have any other
                    comments you'd like to come with?
   - Interviewee :: Well I might want to go with certain people for certain
                    things, but not others.
   - Interviewee :: I think that's all.
   - Interviewer :: Ok, thank you :)
   - Interviewee :: You're welcome!
** Interview two
   - Interviewer :: So, first off, are you okay with the transcript of this
                    interview appearing in my report, scrubbed of names?
   - Interviewee :: yep
   - Interviewer :: ok, good. How do you usually plan small events like movie
                    nights, lunch, or similar?
   - Interviewee :: depending on the circle of friends, i do it via im/irc then
                    generally send out an event notice on gcal or facebook
   - Interviewer :: Do you find that this procedure is needlessly complicated?
   - Interviewee :: it could definitely be streamlined, but it's better than it
                    used to be
   - Interviewer :: Have you ever used location-based services such as Gowalla,
                    Foursquare, Yelp, Facebook places or similar?
   - Interviewee :: i've used yelp heavily, mainly to find places to go
   - Interviewer :: Any particular reason you don't use Gowalla or Foursquare?
   - Interviewee :: i've never tried gowalla, but i saw no benefits to
                    foursquare in my limited use
   - Interviewer :: If you could improve on the event planning procedure you
                    use, how would you do it?
   - Interviewee :: i've never really thought about it, but some facility by
                    which people can more easily figure out when their friends
                    are free for things would make things easier
   - Interviewer :: Interesting
   - Interviewer :: Would you use an application that lets you plan these kinds
                    of single events on a map, notify/invite you friends, and
                    optionally uses location to track check-ins to events?
   - Interviewee :: if it makes the actual planning part of it easier
                    (especially scheduling negotiations), absolutely
   - Interviewee :: otherwise, possible
   - Interviewer :: Would you allow the application access to your google
                    calendar schedule (or similar) so it can notify your friends
                    of your availability when they plan events?
   - Interviewee :: yes
   - Interviewer :: Would you allow it access to your facebook info, so it can
                    use your profile data to better recommend/rank events or
                    otherwise use your data to make choosing events to attend to
                    easier?
   - Interviewee :: yes
   - Interviewer :: Would you rather use a friend list, potentially with friend
                    groups, or join "communities" to control who sees your
                    events? A community in this context is a group of people
                    with some relation to eachothers
   - Interviewee :: i don't have a preference either way -- i'd likely use both.
   - Interviewer :: ok, I think that should be all my questions, any other
                    comments?
   - Interviewee :: not off the top of my head
   - Interviewer :: ok, thanks :)
